object Versions {
  const val androidGradlePlugin = "7.0.0"
  const val depUpdate = "0.36.0"
  const val kotlin = "1.5.31"
  const val appcompat = "1.4.0-beta01"
  const val coreKtx = "1.7.0-beta02"
  const val constraintLayout = "2.1.1"
  const val material = "1.4.0"
  const val testRunner = "1.4.0"
  const val espressoCore = "3.4.0"
  const val testRules = "1.4.0"
  const val mockk = "1.12.0"
  const val kakao = "2.4.0"
  const val detekt = "1.18.1"
  const val junit = "5.8.1"
  const val assertJ = "3.21.0"
  const val detektCli = "1.9.0"
  const val hiltAndroid = "2.40"
  const val viewModelKtx = "1.3.6"
  const val activityCompose = "1.4.0"
  const val composeMaterial = "1.0.4"
  const val composeAnimation = "1.0.4"
  const val composeTooling = "1.0.4"
  const val composeViewModel = "2.4.0"
  const val composeThemeAdapter = "1.0.4"
  const val composeConstraint = "1.0.0-rc01"
}

object GradlePlugins {
  const val androidGradle = "com.android.tools.build:gradle:${Versions.androidGradlePlugin}"
  const val kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
  const val detekt = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:${Versions.detekt}"
  const val depUpdate = "com.github.ben-manes:gradle-versions-plugin:${Versions.depUpdate}"
  const val hilt = "com.google.dagger:hilt-android-gradle-plugin:${Versions.hiltAndroid}"
}

object Libs {
  const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Versions.kotlin}"
  const val appCompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
  const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
  const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
  const val material = "com.google.android.material:material:${Versions.material}"
  const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hiltAndroid}"
  const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.hiltAndroid}"
  const val hiltInstrumentation = "com.google.dagger:hilt-android-testing:${Versions.hiltAndroid}"
  const val testRunner = "androidx.test:runner:${Versions.testRunner}"
  const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espressoCore}"
  const val testRules = "androidx.test:rules:${Versions.testRules}"
  const val mockkAndroid = "io.mockk:mockk-android:${Versions.mockk}"
  const val kakao = "com.agoda.kakao:kakao:${Versions.kakao}"
  const val detektApi = "io.gitlab.arturbosch.detekt:detekt-api:${Versions.detekt}"
  const val detektTest = "io.gitlab.arturbosch.detekt:detekt-test:${Versions.detekt}"
  const val junitApi = "org.junit.jupiter:junit-jupiter-api:${Versions.junit}"
  const val junitParams = "org.junit.jupiter:junit-jupiter-params:${Versions.junit}"
  const val assertJ = "org.assertj:assertj-core:${Versions.assertJ}"
  const val junitEngine = "org.junit.jupiter:junit-jupiter-engine:${Versions.junit}"
  const val detektCli = "io.gitlab.arturbosch.detekt:detekt-cli:${Versions.detektCli}"
  const val viewModelKtx = "androidx.fragment:fragment-ktx:${Versions.viewModelKtx}"
  const val activityCompose = "androidx.activity:activity-compose:${Versions.activityCompose}"
  const val composeMaterial = "androidx.compose.material:material:${Versions.composeMaterial}"
  const val composeAnimation = "androidx.compose.animation:animation:${Versions.composeAnimation}"
  const val composeTooling = "androidx.compose.ui:ui-tooling:${Versions.composeTooling}"
  const val composeViewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.composeViewModel}"
  const val composeThemeAdapter = "com.google.android.material:compose-theme-adapter:${Versions.composeThemeAdapter}"
  const val composeConstraint = "androidx.constraintlayout:constraintlayout-compose:${Versions.composeConstraint}"
}
